// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: group.proto

package server

import (
	"context"

	"im_message/app/group/rpc/internal/logic"
	"im_message/app/group/rpc/internal/svc"
	"im_message/proto/group"
)

type GroupClientServer struct {
	svcCtx *svc.ServiceContext
	group.UnimplementedGroupClientServer
}

func NewGroupClientServer(svcCtx *svc.ServiceContext) *GroupClientServer {
	return &GroupClientServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupClientServer) AddFriend(ctx context.Context, in *group.AddFriendRequest) (*group.AddFriendResponse, error) {
	l := logic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

func (s *GroupClientServer) HandleFriend(ctx context.Context, in *group.HandleFriendRequest) (*group.HandleFriendResponse, error) {
	l := logic.NewHandleFriendLogic(ctx, s.svcCtx)
	return l.HandleFriend(in)
}

func (s *GroupClientServer) GroupUserList(ctx context.Context, in *group.GroupUserListRequest) (*group.GroupUserListResponse, error) {
	l := logic.NewGroupUserListLogic(ctx, s.svcCtx)
	return l.GroupUserList(in)
}

func (s *GroupClientServer) UserGroupList(ctx context.Context, in *group.UserGroupListRequest) (*group.UserGroupListResponse, error) {
	l := logic.NewUserGroupListLogic(ctx, s.svcCtx)
	return l.UserGroupList(in)
}

func (s *GroupClientServer) MessageGroupInfoList(ctx context.Context, in *group.MessageGroupInfoListRequest) (*group.MessageGroupInfoListResponse, error) {
	l := logic.NewMessageGroupInfoListLogic(ctx, s.svcCtx)
	return l.MessageGroupInfoList(in)
}

func (s *GroupClientServer) AddGroupChat(ctx context.Context, in *group.AddGroupChatRequest) (*group.AddGroupChatResponse, error) {
	l := logic.NewAddGroupChatLogic(ctx, s.svcCtx)
	return l.AddGroupChat(in)
}

func (s *GroupClientServer) CreateGroupChat(ctx context.Context, in *group.CreateGroupChatRequest) (*group.CreateGroupChatResponse, error) {
	l := logic.NewCreateGroupChatLogic(ctx, s.svcCtx)
	return l.CreateGroupChat(in)
}

func (s *GroupClientServer) GetFriendListByUserId(ctx context.Context, in *group.FriendListRequest) (*group.FriendListResponse, error) {
	l := logic.NewGetFriendListByUserIdLogic(ctx, s.svcCtx)
	return l.GetFriendListByUserId(in)
}
