// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: user.proto

package server

import (
	"context"

	"im_message/app/user/rpc/internal/logic"
	"im_message/app/user/rpc/internal/svc"
	"im_message/proto/user"
)

type UserClientServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserClientServer
}

func NewUserClientServer(svcCtx *svc.ServiceContext) *UserClientServer {
	return &UserClientServer{
		svcCtx: svcCtx,
	}
}

func (s *UserClientServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserClientServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserClientServer) PersonalInfo(ctx context.Context, in *user.PersonalInfoRequest) (*user.PersonalInfoResponse, error) {
	l := logic.NewPersonalInfoLogic(ctx, s.svcCtx)
	return l.PersonalInfo(in)
}

func (s *UserClientServer) ResetPassword(ctx context.Context, in *user.ResetPasswordRequest) (*user.ResetPasswordResponse, error) {
	l := logic.NewResetPasswordLogic(ctx, s.svcCtx)
	return l.ResetPassword(in)
}

func (s *UserClientServer) UpdateOnlineStatus(ctx context.Context, in *user.UpdateOnlineStatusRequest) (*user.UpdateOnlineStatusResponse, error) {
	l := logic.NewUpdateOnlineStatusLogic(ctx, s.svcCtx)
	return l.UpdateOnlineStatus(in)
}

func (s *UserClientServer) GetOnlineStatus(ctx context.Context, in *user.GetOnlineStatusRequest) (*user.GetOnlineStatusResponse, error) {
	l := logic.NewGetOnlineStatusLogic(ctx, s.svcCtx)
	return l.GetOnlineStatus(in)
}
