// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6,max=16"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type ModifyPersonalInfoRequest struct {
	NickName  string `json:"nickName,optional" validate:"-"`                 // 可选
	Gender    int64  `json:"gender,optional,default=0" validate:"oneof=0 1"` // 默认为0
	AvatarUrl string `json:"avatarUrl,optional" validate:"url"`              // 可选
}

type ModifyPersonalInfoResponse struct {
	Success bool `json:"success"`
}

type PersonalInfoRequest struct {
}

type PersonalInfoResponse struct {
	UserId    int64  `json:"userId"`
	NickName  string `json:"nickName"`
	Gender    int64  `json:"gender"`
	Email     string `json:"email"`
	AvatarUrl string `json:"avatarUrl"`
}

type QueryUserInfoRequest struct {
	UserId int64 `json:"userId" validate:"required"`
}

type RegisterRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6,max=16"`
	NickName string `json:"nickName,optional" validate:"-"`                 // 可选
	Gender   int64  `json:"gender,optional,default=0" validate:"oneof=0 1"` // 默认为0
}

type RegisterResponse struct {
}

type ResetPasswordRequest struct {
	Email       string `json:"email" validate:"required,email"`
	OldPassword string `json:"oldPassword" validate:"required,min=6,max=16"`
	NewPassword string `json:"newPassword" validate:"required,min=6,max=16"`
}

type ResetPasswordResponse struct {
	Success bool `json:"success"`
}
